Fixed type getting
FXinnovation/azure_metrics_exporter pull request #28
Opened 2019-12-09 21:36 UTC by vincentcreusot

2019-12-09 21:49 UTC, louisfelix requested changes
This is promising. But you are duplicating `CreateResourceLabels` logic.
I would have reused `CreateResourceLabels`, maybe by renaming it something more generic, like `ParseResourceID`, and then call it from `batchLookupResources`

2019-12-10 02:41 UTC, vincentcreusot commented
> This is promising. But you are duplicating `CreateResourceLabels` logic.
> I would have reused `CreateResourceLabels`, maybe by renaming it something more generic, like `ParseResourceID`, and then call it from `batchLookupResources`

To be honest the only duplicate is one line, the split ... so for the sake of simplicity I would keep that this way, and you know how I'm a factorizing fan ;-)

2019-12-10 02:55 UTC, louisfelix commented
> To be honest the only duplicate is one line, the split ... so for the sake of simplicity I would keep that this way, and you know how I'm a factorizing fan ;-)

You are right, I read too fast, this is not the same goal that has `CreateResourceLabels`

2019-12-10 02:55 UTC, louisfelix approved these changes

2019-12-10 16:26 UTC, merged